---
title: "Untitled"
output: pdf_document

linkcolor: RoyalBlue
urlcolor: RoyalBlue
fontsize: 12pt

bibliography: 
  - references.bib
---


Estación Biológica de Doñana (EBD-CSIC), E-41092 Seville, Spain

# Abstract

The rapid conversion of natural habitats to anthropogenic landscapes is threatening insect pollinators worldwide, raising concern on the consequences for their fundamental role in ecosystems for fruit and seed production. However, not all pollinators are negatively affected by habitat conversion, but some find in anthropogenic landscapes appropriate resources to survive and reproduce. Why some animals can thrive in anthropogenic environments that most species cannot tolerate remains insufficiently understood, but it might in part reflect enhanced behavioural plasticity to exploit new resource opportunities. While this hypothesis has received ample support in studies of vertebrates, it is less obvious whether the small brain of insects can offer enough behavioural plasticity to cope with the many challenges of anthropogenic habitats. To address this issue, we measured brains for 145 individuals from 44 species of bees —the most important group of pollinators— from North America and Europe, and compared them with detailed information on habitat preferences and population trends. Our analyses revealed that bees that prefer forest habitats had smaller brains relative to their body size, but those who prefer urban habitats tended to have larger brains compared to forest dwellers. However, we found no evidence that either larger brains or a preference for urban habitats are associated with positive population trends. These results suggest that a large brain can help maintaining bee urban populations, but also highlight that being tolerant to urbanisation is not enough to compensate for the worldwide decline of their populations.

Keywords:

\textbf{Author for correspondence:}

# Introduction

Pollination is a fundamental ecosystem service that connects the earth’s vegetation and human economy. Pollination services are performed by both managed and wild pollinators, mostly bees (James & Pitts Singer, 2008; Winfree et al., 2011), both of which might be affected by a range of current and projected human-related environmental changes. There are indeed clear shreds of evidence of recent declines in pollinator populations (Bartomeus et al., 2018), and parallel declines in the plants that rely upon them (Potts et al., 2010; Scheper et al., 2014). For example, in the UK, the third part of wild pollinator species has decreased from 1980 to 2013 (Powney et al., 2019), including six of all 16 non-parasitic bumblebees (Williams & Osborne, 2009). The decline of pollinators currently observed is projected to increase in the future (Dormann et al., 2008). Because most wild plant species (80%) and crop species (75%) are directly dependent on insect pollination for fruit and seed production (Klein et al., 2007; Ollerton et al., 2011), there is an increasing concern that the loss of pollinators from both natural communities and agricultural areas will have severe negative consequences for ecosystem functions and services (Ashman et al., 2004; Klein et al., 2007).
Although the reason why many pollinator are declining is insuficiently understood, a factor that is considered central is the loss and alteration of their habitats (Brown & Paxton, 2009; Natural Research Council, 2006). The destruction and fragmentation of natural habitats and their replacement by anthropogenic landscapes present new challenges for survival and reproduction of organisms, increasing the risk of extinction by negative population growth (Brown & Paxton, 2009; Natural Research Council, 2006). However, not all pollinators species are equally affected by habitat loss and alteration. In bees, for example, there are also “winners” —like Bombus terrestris (Rasmont et al., 2008)— that are able to thrive in human-altered environments, and there are also other species that although do not proliferate in such environments can at least maintain self-sustaining populations (Biesmeijer et al., 2006; Bartomeus et al., 2013; Reemer et al., 2012; Collado et al., 2019). Human-dominated habitats —notably cities— offer unique ecological opportunities in the form of new nesting spots, reduced predation pressure and high food availability associated with non-indigenous plants (Cane et al., 2006; Winfree et al., 2007; Collado et al., 2019). Although variation across species in tolerance to habitat loss and alteration is likely to have important demographic consequences, whether this is the reason why some pollinators are declining while others are increasing is currently unknown. Hence, the ability to adapt to human-dominated new habitats and to exploit new opportunities have become important for species to thrive (Manenti et al., 2013). For species that tolerate human-related disturbances, human-dominated habitats —notably cities— offer unique ecological opportunities in the form of new nesting spots, reduced predation pressure and high food availability associated with non-indigenous plants (Cane et al., 2006; Winfree et al., 2007; Collado et al., 2019). The question is then why only some species are able to enjoy the benefits of an urban life.In a novel environment, the chances to successfully survive and reproduce largely depends on cognition, that is, the processes involved in gathering, storing and reacting to environmental information. Cognitive limitations have thus help explaining the low success of many species in novel environments in general, and urban areas in particular. For example, reptiles, amphibians and birds that flourished after being introduced to new regions outside their native ranges tend to have larger brains (relative to their body size) than unsuccessful invaders (Sol et al., 2008; Sol et al., 2005; Amiel et al., 2011). In vertebrates, relative brain size is a good proxy of problem-solving and learning (e.g. see chapter 2 of this thesis for its relationship with learning), which can help individuals to cope with the many challenges on novel environments. However, similar evidence is lacking for insects, in part because advanced cognitive abilities were not considered possible with their tiny brains. More important, there was no unequivocal evidence that brain size was related to cognitive performance. However, we now know that bees and other insects have advanced cognition, being able for instance to use tools to resolve new problems and learn socially how to do so (Alem et al., 2016). There is in addition evidence that cognitive differences in the brain are reflected in differences in their brain size (Chapter 2).We used previously published data on bee forest and urban preference (Collado et al., 2019) as opposite points of habitat complexity, expecting to find bigger brain sizes for urban dwellers because a wider array of cognitive abilities are needed to inhabit these habitats. Species population trends were extracted from Bartomeus et al., 2013 and both datasets were crossed with a newly collected brain weight database. We wanted to explore if there is a relationship between brain size, habitat preference, and population trends. Hence, our questions were the following:Are brain sizes, as a proxy of behavioural plasticity, related to habitat preferences?Is population stability related to brain size as it has been seen in other taxa?Are habitat preferences related to population stability? Or alternatively, are urban dwellers populations increasing?

# Methods

**Animals**

Most bees were opportunistically captured by hand netting in different regions of New York State (USA), and complemented with  bees captured from Spain and the Netherlands for species with a holarctic distribution. We captured 145 individuals from 44 species, kept them in cold storage and sent them to the laboratory to be processed. Once the bees were in the laboratory, they were anesthetized in cold (Crook, 2013) and decapitated. Bees were identified by expert taxonomists (Parker Gambino and Ivo Raemakers). The species used for the analysis can be consulted in Table S2. We measured the inter-tegular distance, as it is a good proxy of body size (Kendall et al., 2019). To prevent degradation, the head was fixed in 4% paraformaldehyde with phosphate buffer saline (PBS). Brains were extracted from the head capsule, and tracheae and fat bodies were removed to maximize accuracy in neural tissue weight. Brains extracted were placed on a small piece of tared Parafilm® and exceeding fixative solution was dried from the brain using Kimwipes® tissues. Finally the brain was weighted in a microbalance. Brain weight was used as a proxy of brain size (Sayol et al., 2019 in preparation). 

**Data gathering**

The quantitative data of population trends for North American bees were extracted from Bartomeus et al., 2013, where they analyzed trends for 187 species over time, using data from pinned bees from different North American museums and universities. We assigned the estimated value of their relative change over time models as values of population trends for the 44 species for which we have brain size measurements (positive for increasing populations and negative for decreasing populations). Habitat preferences for USA bee data were extracted from Collado et al., 2019, were habitat preference for forests and urban areas was calculated comparing species occurrence in each habitat to what would be expected if species occur at random using null models. This preference index ranges from 0 (avoidance) to 1 (preference).In order to have a representative value of brain weight and body size per species, we used means of the different collected individuals from each species. Twenty-four individuals with brain weight values one standard deviation higher or lower than the average were removed (see sup mat analysis) because human errors in their measurement are likely with such delicate tissues. Specially, brain weights can give errors due to dehydration or insufficient removal of fat bodies and trachea around the brain. For eusocial species, we only used workers. We estimated relative brain size using residuals from a log-log correlation of brain weight against body size to remove body size allometric relationships. (see Wurm & Fisicaro, 2014) (LM estimate ± SE = 1.88 ± 0.06, p < 0.001, R2= 0.83, n = 163 species). Residuals were calculated using our complete brain weights and body size database.

**Data analysis**

We used Bayesian phylogenetic generalised linear mixed models (BPGMM), as implemented in the package brms (Bürkner, 2017), to assess whether brain sizes, habitat preference and population trends are correlated. In all models, we incorporated a phylogenetic covariance matrix. The phylogeny used were maximum-likelihood phylogenetic trees of the superfamily Apoidea at the genera level modified from (Hedtke et al., 2013, Fig. 1, Fig. S2, Fig. S3). Due to the absence of infrageneric phylogenies for all our genera, we simulated infrageneric polytomies within our phylogeny. Species tips were added to the phylogenetic tree genera nodes as polytomies of equal branch length relative to the genera branch length using the phytools package (version 0.6‐44, Revell, 2012). Because we did not have information on our 3 variables for the 44 species (habitat preference, brain weight and population trends), we used 3 different subsets of our dataset to maximize the sample size in the different models: Relative brain size-habitat preference, population trends-habitat preference and population trends-relative brain size.

# Results

# Discussion


Bees with urban habitat preferences tended to have bigger brains related to their body sizes, and those with forest preferences had relatively smaller brains. Surprisingly, neither brain sizes nor habitat preference explained population trends, against what we expected. Therefore, species with bigger brains appearing on urban habitat can be indicating that while only bees with large cognitive capacities are surviving in these modified environments, they do not have experienced notorious increases in their populations.We hypothesized that bees with bigger brains related to body size should be more flexible in their behaviour because a large brain may confer better cognitive abilities, as it has been observed in some species (Lefebvre et al., 2004) and as we show specifically for bees in relation to learning (Chapter 2 of this thesis). Therefore, to exploit complex urban environments, we expect bigger brains to be required. Urban habitats are typically harsher, with less and/or new resources to explore, also containing new unknown threats and a highly changing environment (Wheater, 1999). Hence, urban dwellers may need to have better cognitive abilities and flexibility in their behavior than the forest dwellers counterpart. Some examples of behaviours needed to survive in urban environments (see Table S2 for a full set of examples) are the use of human-made materials to nest (Allasino et al., 2019) or being able to collect pollen and nectar from exotic flowers from gardens (Lowenstein et al., 2014). We should not expect forested habitats to require such a plastic behaviour because the resources found in these habitats are homogeneous, stable, and bees are already pre-adapted to use them (Smith et al., 2019). In accordance, we found smaller brain sizes than expected by their body sizes in bees that preferred forests indicating that an investment in bigger relative brain sizes is not required. In addition, other traits have already been described to be filtered in anthropogenic land uses, like early spring or brood parasitism (Harrison et al., 2017), which are present in the forest dwellers.
We could not explain population trends with brain size as it happens in other taxa. For example, in birds, brain size is a good predictor of how a population does in the long-term (Shultz, 2005). However, this is not always the case as bigger brains increase the risk of extinction in mammals (González-Voyer et al., 2016). Despite brain weight is relatively easy to measure and standardize with the used protocol, we lack information on certain neuropils size, like mushroom bodies (the suspected centers of cognitive processes in bees), which can be variable even within species (Barth & Heisenberg, 1997; Withers et al., 1995; Fahrbachand & Robinson 1995). Differences in more subtle brain structures could explain differences in behaviours, and in consequence, shed extra light on species population trends. Therefore the isolation and measurement of these neuropils could be interesting because we could get more accurate information. On the other hand, also note that population trends data is hard to find or measure, especially for invertebrate taxa. Long term data is often lacking and we count only with data indirectly taken from museums. This data is also scarce and hard to standardize (Bartomeus et al., 2018), therefore not being optimal for comparative studies of declining or increasing populations (Shultz, 2005). Species body size is generally related to population trends. In mammals, it is known that bigger body sizes decreases population density and increases the risk of extinction (Damuth, 1981; González-Voyer et al., 2016). This relation has also been seen in bees (Scheper et al., 2014). Although body size is directly related to absolute brain size, we did not find a strong correlation between body size and population trends in our subset of North American bees as it was found for the complete set in Bartomeus et al., 2013. Our subset may be biased towards the most common genera and contain fewer species per genus. If the body size-decline relationship occurs mainly within genus, and not across genus, as indicated by the strong phylogenetic signal of body size (Pagel’s λ > 0.9), we may lack the power to detect this variation within genus in our restricted analysis. Population trends or habitat preferences could be explained by the availability of the resources consumed, for example, in the Netherlands, population trends of some bee species are related to the availability of their preferred plants (Scheper et al., 2014). A polylectic diet could help species to adapt to new environments, and we know that species able to forage on crop plant families tend to have stable or increasing populations (Scheper et al., 2014, Bartomeus et al. 2013). If we consider habitats being conditioned by their availability of the preferred resources, then we may be able to explain our link between brain size and preference for certain habitats. For example, differences in bee community composition and abundance are found for oligolectic (i.e.diet specialist bees) associated to their prefered resources along forested gradients (Grundel et al., 2010). Dietary data should be an interesting next step to see if broader (polylectic) or narrower (oligolectic) diet are generally related to habitat preferences and brain sizes. In fact, it has been already described for other taxa a relationship between brain size and diet (DeCasien et al., 2017).Finally, the absence of relationship between urban preferences and increasing population trends is interesting. Despite these bees have found new niches to occupy, they are not increasing its populations but just persisting. The transformation from natural to urban habitats is filtering which species can survive, and hence, biodiversity in urban habitats is usually lower (Collado et al., 2019, Chapter 3 of this thesis). However, survivors are not thriving either in this new conditions. Some negative effects of urbanization have already been studied in bees, like for example, biased sex ratio, with increasing males in urban areas (Fitch et al., 2019) with unknown future population consequences. It should be interesting to fully assess the costs and benefits of living in urban environments, including brain investment and other selected strategies to adapt to the new conditions.


